spring:
  application:
    name: security
  
# JWT ??
jwt:
  secret: mySecretKeyThatIsLongEnoughForHMACAlgorithmAtLeast256BitsLong
  token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400
  
# ??? URL ??
service:
  payment:
    url: http://localhost:8085
  inventory:
    url: http://localhost:8086
  
# ?? ??
logging:
  level:
    com:
      berryweb:
        security: DEBUG
    feign: DEBUG
  
# ?? ??
server:
  port: 8087