spring:
  application:
    name: security
  
  # Spring Cloud 기능 모두 비활성화
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
    openfeign:
      enabled: false

# Eureka 비활성화
eureka:
  client:
    enabled: false

# JWT 테스트 설정
jwt:
  secret: testSecretKeyThatIsLongEnoughForHMACAlgorithmAtLeast256BitsLong
  token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

# 로깅 레벨 낮춤
logging:
  level:
    root: WARN
    com.berryweb.security: INFO